config/routes.rb
Rails.application.routes.draw do
  root 'secrets#index'

  post 'likes/:id' => 'likes#create'

  resources :sessions, :users, :secrets, :comments, :likes

  get '*path' => 'errors#error_404'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :secret

  validates :content, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :secret
end

app/models/secret.rb
class Secret < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :users_liked, through: :likes, source: :user

  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :secrets, dependent: :destroy
	has_many :secrets
	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	#to get the likes of instances of User
	has_many :secrets_liked, through: :likes, source: :secret

	EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
	validates :username, :email, presence: true
	validates :username, uniqueness: { case_sensitive: false }
	validates :password, length: { minimum: 4 }, presence: true, on: :create
	validates :password_confirmation, presence: true, on: :create
	validates :email, format: { with: EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	before_save do 
	  	self.email.downcase!
	end 
	before_update do
	    check_password
	end 

	private
	    def check_password
	        is_ok = self.password.nil? || self.password.empty? || self.password.length >=4 
	        self.errors[:password] << "password is too short (minimum is 4 characters)" unless is_ok
	    end
end

app/models/userme.rb
class Userme < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	protect_from_forgery with: :exception

  	helper_method :current_user
 

	private
		def current_user
	 	    User.find(session[:user_id]) if session[:user_id]
	    end
		def require_login
		    redirect_to '/sessions/new' unless current_user
		end
		def logged_in
		    redirect_to '/secrets' if current_user
		end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :all_tasks, only: [:index, :create, :update, :destroy]

	def create
		comment = Comment.create(user: current_user, secret: Secret.find(comment_params[:id]), content: comment_params[:content])
		if comment.valid?
			comment.save
			# flash[:secret_comment_success] = "Comment added"

			respond_to do |format|
				format.html{ redirect_to root_path }
				format.js { }
			end
		else
			flash[:secret_comment_error] = comment.errors.full_messages
			redirect_to '/'
		end
	end
	private
		def comment_params
			params.require(:comment).permit(:content, :id)
		end
		def all_tasks
			@comments = Comment.all
			@secrets = Secret.all.reverse
		end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
	def error_404
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :all_tasks, only: [:create, :destroy]

	def create
		like = Like.new(secret: Secret.find(params[:id]), user: current_user)
	  	like.save
		respond_to do |format|
	  		format.html { redirect_to root_path }
	  		format.js { }
	  	end
	end

	def destroy
		likes = Like.where(user: current_user, secret: Secret.find(params[:id]))
	    likes.each{ |like| like.destroy } 
	  	respond_to do |format|
	  		format.html { redirect_to root_path }
	  		format.js { }
	  	end
	end

	private
		def all_tasks
			@secrets = Secret.all.reverse
			@comments = Comment.all
			# @likes = Like.all
		end
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
	before_action :require_login
	before_action :all_tasks, only: [:index, :create, :update, :destroy]

  	def index
  		@secrets = Secret.all.reverse
  	end

  	def create
  		@secret = Secret.new(content: secret_params['content'], user: current_user)	
  		if @secret.valid? == true
  			@secret.save
        
		    respond_to do |format|
		        format.html { redirect_to root_path }
				format.js { }
		    end
  		else
	  		flash[:secret_errors] = @secret.errors.full_messages 
	  		redirect_to '/'
	  	end
  	end

	def edit
		@secret = Secret.find(params[:id])
		respond_to do |format|
			format.html { }
			format.js { }
		end
	end

	def update
		@user_secrets = Secret.where(user: current_user)
		secret = Secret.update params[:id], content: secret_params[:content]
	    if secret.save
	    	flash[:success] = "Secret updated"
	        respond_to do |format|
	        	format.html { redirect_to user_path }
	        	format.js {}
	        end
	    else
	      flash[:danger] = secret.errors.full_messages
	      redirect_to edit_secret_path
	    end
	end

	def destroy
		# make this instance variable available to the partial
		@user_secrets = Secret.where(user: current_user)
		@secret = Secret.find(params[:id])
		@secret.destroy
	    respond_to do |format|
	    	format.html { redirect_to :back }
	    	format.js { }
	    end
	end

	private
		def secret_params
			params.require(:secret).permit(:content)
		end
		def all_tasks
			@secrets = Secret.all
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]
  before_action :logged_in, only: [:new]
  
	def new
	end

	def create
		user = User.find_by_username(params[:session][:username])
		if params[:session][:username] == ""
			flash[:danger] = "Username can't be blank"
			redirect_to new_session_path
		elsif params[:session][:password] == ""
			flash[:danger] = "Password can't be blank"
			redirect_to new_session_path
		elsif !user
      		flash[:danger] = "username not found"
      		redirect_to new_session_path 
    	elsif !user.authenticate(params[:session][:password])
      		flash[:danger] = "wrong password"
      		redirect_to new_session_path
      	else
      		session[:user_id] = user.id
      		flash[:success] = "Welcome #{current_user.username}"
      		redirect_to secrets_path
      	end
	end 

	def destroy
  		session[:user_id] = nil
  		flash[:success] = "you have signed out"
  		redirect_to new_session_path
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, except: [:new, :create]
    before_action :all_tasks, only: [:show]
	# respond_to :html, :js

  	def index
  	end

  	def create
  		user = User.create(register_params)
  		if user.valid? == true
  			user.save
  			flash[:success] = "Registration successful" 
  			redirect_to new_session_path 
  		else
  			flash[:danger] = user.errors.full_messages
  			redirect_to new_user_path
      	end
  	end

  	def new
  		@user = User.new
 	end

    def show
       @user = User.find(session[:user_id]) 
       @user_secrets = Secret.where(user: current_user).reverse
       # @secrets_liked = current_user.secrets_liked.reverse
    end

    def edit
        @user = User.find(current_user)
        respond_to do |format|
            format.html { }
            format.js { }
        end
    end

    def update
        @user = User.update params[:id], update_params 
        if @user.save
            flash[:success] = "username updated"
            respond_to do |format|
                format.html { redirect_to user_path }
                format.js { }
            end
        else
            flash[:danger] = @user.errors.full_messages
            redirect_to edit_user_path
        end
    end

 	private
 		def register_params
 			params.require(:user).permit(:username, :email, :password, :password_confirmation)
 		end

        def update_params
            params.require(:user).permit(:username)
        end

        def all_tasks
            @secrets = Secret.all
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.js.erb
$('#my-secrets').html("<%= j (render 'secrets/task') %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge"> 
  	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="width=device-width, initial-scale=1">
    <meta name="description" content="Kevin Bundi - Secrets App">
    <meta name="author" content="Kevin Bundi">
	<title>Secrets</title>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   	<%= csrf_meta_tags %>

  	<%= google_webfonts_init({
    	google: ['Roboto Slab', 'Roboto', 'Caveat']
  	}) %> 
</head>
<body>
  <div class="container">
  	<% if current_user %>
  		<%= render "shared/header" %>
  	<% end %>
  	<%= yield %>
  </div>

</body>
</html>

app/views/likes/create.js.erb
$('#my-secrets').html("<%= j (render 'secrets/task') %>")

app/views/likes/destroy.js.erb
$('#my-secrets').html("<%= j (render 'secrets/task') %>")

app/views/secrets/_postForm.html.erb
<%= form_for Secret.new, remote: true do |f| %>
	<div class="form-group">
		<%= f.text_area :content, class: "form-control", rows: "3", placeholder: "Post a secret" %> 
	</div>
	<div class="form-group secrets_post_button clearfix">
		<%= f.submit value: "Post", class: "btn btn-info pull-right" %>
	</div>	
<% end %>

app/views/secrets/_task.html.erb
<% @secrets.each do |secret|%> 
	<div class="secrets_content form-group">
		<img src="<%= asset_path('anonymous.png') %>" alt="anonymous" id="profile_icon" class="img-thumbnail"><strong class="my-color" style="margin-left: 0.50rem;" "><%= secret.user.username %></strong>
		<p class="secrets_content_p"><%= secret.content %>
			<% if secret.user_id == current_user.id %>
				<%= link_to "edit", edit_secret_path(secret), remote: true, class: "my_links" %>
			<% end %>
		</p>
		<%if secret.users_liked.include? current_user%>
			<div class="secrets_content_in">
				<ul class="like_comment">
					<li><span class=""><i class="fa fa-thumbs-down" aria-hidden="true"></i></span>
					<%= link_to "unlike", like_path(secret.id), class: "my_links black", method: 'delete', remote: true %>
					<!-- <span class=""><i class="fa fa-comment" aria-hidden="true"></i></span> -->
					<!-- <li class="my_links user_comment"><a href="#">comment</a></li> -->
				</ul>
			</div>
		<% else %>
			<div class="secrets_content_in">
				<ul class="like_comment">
					<li><span class=""><i class="fa fa-thumbs-up" aria-hidden="true"></i></span>
					<%= link_to "like", like_path(secret.id), class: "my_links black", method: 'post', remote: true %>
					<!-- <span class=""><i class="fa fa-comment" aria-hidden="true"></i></span> -->
					<!-- <li class="my_links user_comment"><a href="#">comment</a></li> -->
				</ul>
			</div>
		<%end%> 

		

		<p class="my_links secrets_content_p"><%= Secret.find(secret.id).likes.count %> likes</p>

		<hr class="the_line">
		<div class="secrets_comments form-group">
			<% secret.comments.each do |s| %>
				<p class="my_links my_italics"><strong class="my-color" "><%= s.user.username %>:</strong> <%= s.content %></p>
			<% end %>
		</div>	


		<p class="success_p"><%= flash[:secret_comment_success] %><p>

		<% if flash[:secret_comment_error] %>
			<% flash[:secret_comment_error].each do |error| %>
				<p class="error_p"><%=error %></p>
			<% end %>
		<% end %>

		<%= form_for Comment.new, remote: true do |f| %>
			<%= f.hidden_field :id, value: secret.id %>
			<div class="form-group input-group">
				<%= f.text_area :content, class: "form-control", rows: "1", placeholder: "Add a comment" %>
				<button type="submit" class="btn btn-info btn-sm"><span class=""><i class="fa fa-paper-plane" aria-hidden="true"></i></span></button>
			</div>
		<% end %>
	</div>
<% end %>
				
				
			

app/views/secrets/_updateForm.html.erb
<% if flash[:danger] %>
	<div class="alert alert-info alert-dismissable fade show">
		<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		<% flash[:danger].each do |e| %>
			<%= e %>
		<% end %>
	</div>
<% end %>

<%= form_for @secret, remote: true do |f| %>
	<div class="form-group">
		<%= f.text_area :content, class: "form-control", rows: "3", placeholder: "Post a secret", autofocus: "autofocus" %> 
	</div>
	<div class="form-group secrets_post_button clearfix">
		<%= f.submit value: "Update secret", class: "btn btn-info pull-right" %>
	</div>	
<% end %> 

app/views/secrets/_usersSecrets.html.erb
<% if @user_secrets %>	
	<div id="secrets_content_hse">
		<h5>Your Secrets</h5>
		<% @user_secrets.each do |secret| %>
			<div class="form-group secrets_content">
				<p>
					<%= secret.content %>
					<%= link_to 'edit', edit_secret_path(secret.id), remote: true, class: "my_links" %> |
					<%= link_to 'delete', secret_path(secret.id), remote: true, method: "delete", data: { confirm: 'confirm delete' }, class: "my_links" %>
				</p>
				<p class="my_links"><%= Secret.find(secret.id).likes.count %> likes</p>
			</div>
		<%end%>
	</div> 
<% end %>

app/views/secrets/create.js.erb
$('#my-secrets').html("<%= j (render 'task') %>")
$('#my-postForm').html("<%= j (render 'postForm') %>") 

app/views/secrets/destroy.js.erb
$('#userSecrets').html("<%= j (render 'usersSecrets') %>")

app/views/secrets/edit.html.erb
<%= render 'updateForm' %>

app/views/secrets/edit.js.erb
$('#userSecrets').html("<h4>Edit secret<h4/> <%= j (render 'updateForm') %>")
$('#my-postForm').html("<h4>Edit secret<h4/> <%= j (render 'updateForm') %>")

app/views/secrets/index.html.erb
<% if flash[:success] %>
	<div class="alert alert-info alert-dismissable fade show">
		<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		<%= flash[:success] %>
	</div>
<% end %>
<div class="secrets_main col-md-8">
	
	<% if flash[:secret_errors] %></form>
		<% flash[:secret_errors].each do |e| %>
			<p class="my_links" style="color:red"><%=e%></p>
		<%end%>
	<%end%>
	
	<div id="my-postForm">
		<%= render 'postForm' %>
	</div>

	<div id="my-secrets">
		<%= render 'task' %>
	</div>
	
</div> 

app/views/secrets/update.js.erb
$('#userSecrets').html("<%= j (render 'usersSecrets') %>")
$('#my-postForm').html("<%= j (render 'postForm') %>")

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse navbar-toggleable-sm bg-faded justify-content-center fixed-top my_navbar">
	<div class="container">
		    <button class="navbar-toggler navbar-toggler-right" id="my_navabar_button_toggle" type="button" data-toggle="collapse" data-target="#my_collapsingNavbar" aria-expanded="false">
		        <span class="navbar-toggler-icon"></span>
		    </button>
	    <ul id="home_ul" class="navbar-brand d-flex w-50 mr-auto my_navbar_brand">
	    	<div class="my-auto">
		    	<a href="/"><i class="fa fa-home fa-2x" aria-hidden="true"></i></a>
		    </div>
		    <div class="my-auto"> <!-- vertical align -->
		    	<a id="secrets_anchor_tag" href="/">Secrets</a>
		    </div>
		</ul>
	    <div class="navbar-collapse collapse my_collapse" id="my_collapsingNavbar">
	        <ul class="nav navbar-nav ml-auto w-100 justify-content-end">
	            <li class="nav-item profile_signout">
	                <a class="nav-link" href="/users/<%=current_user.id%>"><i class="fa fa-user fa-2x" aria-hidden="true"></i> <%= current_user.username %></a>
	            </li>
	            <li role="seperator" class="dropdown-divider"></li>
	            <li class="nav-item profile_signout">
	                <a class="nav-link" href="/sessions/<%=current_user.id%>" data-method="delete""><i" class="fa fa-sign-out fa-2x" aria-hidden="true"></i></a>
	            </li>
	        </ul>
	    </div>
	</div> <!-- end of div.container -->
</nav>

app/views/users/_registrationForm.html.erb
<%= form_for @user do |f| %>
	<h2 class="login_heading" style="background-color: #015c77;"> <span><i class="fa fa-user-plus" aria-hidden="true"></i></span> Sign Up</h2>
	<div class="form-group input-group margin-bottom-sm">
		<span class="input-group-addon"><i class="fa fa-user fa-fw" aria-hidden="true"></i></span>
		<%= f.text_field :username, placeholder: "Username", class: "form-control" %>
	</div>
	<div class="form-group input-group margin-bottom-sm">
		<span class="input-group-addon"><i class="fa fa-envelope-o fa-fw" aria-hidden="true"></i></span>
		<%= f.email_field :email, placeholder: "Email Address", class: "form-control" %>
	</div>
	<div class="form-group input-group margin-bottom-sm">
		<span class="input-group-addon"><i class="fa fa-key fa-fw" aria-hidden="true"></i></span>
		<%= f.password_field :password, placeholder: "Password", class: "form-control" %>
	</div>
	<div class="form-group input-group margin-bottom-sm">
		<span class="input-group-addon"><i class="fa fa-key fa-fw" aria-hidden="true"></i></span>
		<%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.submit value: "Join", class: "btn btn-info btn-block" %>
	</div>
<% end %>

app/views/users/_updateUserForm.html.erb
<div class="col-md-6 secrets_main">
	<% if flash[:danger] %>
 		<% flash[:danger].each do |msg| %>
 			<div class="alert alert-danger alert-dismissable fade show">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
					<p class="error_p"><%= msg %></p>
			</div>
 		<%end%>
 	<%end%>

	<h6>Change Username</h6>
	<%= form_for @user, remote: true do |f| %>
		<div class="form-group ">
			
			<%= f.text_field :username, class: "form-control" %>
			<%= f.submit value: "Update", class: "btn btn-info pull-right", id: "my-update-btn" %>
		</div>
		<div class="form-group">
			
		</div>
	<% end %>
</div>

app/views/users/_usersName.html.erb
<% if flash[:success] %>
	<div class="alert alert-info alert-dismissable fade show">
		<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		<%= flash[:success] %>
	</div>
<% end %>

<h1><%=@user.username%>
	<%= link_to 'edit', edit_user_path(@user.id), remote: true, class:"my_links" %>
</h1>

app/views/users/edit.html.erb
<%= render 'updateUserForm' %>

app/views/users/edit.js.erb
$('#userName').html("<%= j (render 'updateUserForm') %>") 

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="col-md-6 login">
	<div class="link">
		<% if flash[:danger] %>
			<div class="alert alert-danger alert-dismissable fade show">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<% flash[:danger].each do |error| %>
					<li style="list-style: none;"><%= error %></li>
				<% end %>
			</div>
		<% end %>
	</div>
	<%= render 'registrationForm.html' %>
	<p style="font-size:13px;">Already have an account? <%= link_to 'Sign in', new_session_path %></p>
</div>

app/views/users/show.html.erb
<div class="secrets_main col-md-8">
	<div class="form-group" id="userName">
		<%= render 'usersName' %>
	</div>
	
	<div id="userSecrets">
		<%= render 'secrets/usersSecrets' %>
	</div>
</div>

app/views/users/update.js.erb
$('#userName').html("<%= j (render 'usersName') %>")